### PR TITLE
Syntax highlighting

### PR DESCRIPTION
**Pull request by x1y**
In this branch I added syntax highlighting and changed some styling. The multi-distro image page is used as an example there.

@giorez, feel free to test this branch and give feedback.

### CODE REVIEW

**Comment by giorez** [comment]
wow, I really like it. Personally I'd would prefer a lighter background color that coding block, something like dark gray. Full black kill the other content as far I can feel. Anyway is a really big improvement. Thanks for sharing.

PS. I have some improvements for the Multi Distribution content, and a fix for Sailfish block. I'm almost done.

**Comment by giorez** [comment]
> > wow, I really like it. Personally I'd would prefer a lighter background color that coding block, something like dark gray. Full black kill the other content as far I can feel, Maybe because the normal text uses a thin font (I like thin fonts). On my hugo server I don't see any colored highlight, just white text on black background. Anyway is a really big improvement. Thanks for sharing.
> > PS. I have some revisions for the Multi Distribution content, and a fix for Sailfish block. I'm almost done.
> 
> That is a dark grey but I will try other themes. You can test them at https://spsarolkar.github.io/rouge-theme-preview/, the selected one is "Molokai" (with L). We can try a light theme like base16.

my first choise would be monokai, second base16.solarized.dark

**Comment by giorez** [comment]
I re-checked but still no color on syntax. 
Screenshot from 2024-03-14 07-14-52

**Comment by Pavlos1** [comment]
@giorez `sudo apt install ruby-rouge`

**Comment by Pavlos1** [comment]
Looks good! It would be nice to get file listings working as well.

For example:

```asciidoc
[source,shell,foo.sh]
----
echo "This is a short line."
echo "This is a long line. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
echo "This is another short line."
----
```

produces the following render (on chromium; firefox is similar):

screenshot_006

Issues:

* File name (`foo.sh`) is not displayed. (Unless this is intended behaviour?)
* Line numbers do not line up when long lines get wrapped.
* Hyphenation on line-wrap is unadvisable for code/file listings.

**Comment by giorez** [comment]
> @giorez `sudo apt install ruby-rouge`

thanks!

**Comment by giorez** [comment]
> Looks good! It would be nice to get file listings working as well.
> 
> For example:
> 
> ```
> [source,shell,foo.sh]
> ----
> echo "This is a short line."
> echo "This is a long line. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
> echo "This is another short line."
> ----
> ```
> 
> produces the following render (on chromium; firefox is similar):
> 
> screenshot_006
> 
> Issues:
> 
>     * File name (`foo.sh`) is not displayed. (Unless this is intended behaviour?)
> 
>     * Line numbers do not line up when long lines get wrapped.
> 
>     * Hyphenation on line-wrap is unadvisable for code/file listings.

I agree. Good job.

**Comment by giorez** [comment]
> @giorez `sudo apt install ruby-rouge`

now sintax is colored. it looks great the new text style. Pls tell me when the styling upgrade is done, so i can send you the last revisions of Multi Distribution content, and a fix for Sailfish block. 
thanks

**Comment by Pavlos1** [comment]
Mea culpa .. the third positional positional argument [just enables line numbering](https://docs.asciidoctor.org/asciidoc/latest/verbatim/source-highlighter/#enable-line-numbering).

Notably:

>The value of the positional attribute doesn’t matter, though it’s customary to use linenums.

**Comment by giorez** [comment]
I just refreshed locally hugo server, with updated sito repo. In the coding block I see everywhere a thick gery border on right and botton sides.
Screenshot from 2024-03-17 19-20-55

**Comment by giorez** [comment]
> Should be fixed now. I used the wrong "overflow" command and didn't test under Chromium.

fixed, thanks

**Pull request merged**
